"""add_reprint_date_to_notifications

Revision ID: c2e8c287ff78
Revises: 37f990ee0204
Create Date: 2026-03-30 15:02:56.907534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e8c287ff78'
down_revision: Union[str, None] = '37f990ee0204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reprint_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reprint_date')
    # ### end Alembic commands ###
